version: '3'

services:

  xampp:
    build: 
      context: ./.docker/xampp
      dockerfile: DockerFile
    platform: linux/x86_64
    working_dir: /opt/lampp/htdocs/www
    container_name: test_libXampp
    restart: always
    volumes:
      - ./source:/opt/lampp/htdocs/www
      - test_lib-data-volume:/opt/lampp
    command: bash -c " /opt/lampp/lampp start && tail -f .env"
    ports:
      - "3306:3306"
      - "80:80"
      - "8000:8000"
      - "9000:9000"
    networks:
      - test_lib-networks
  
networks:
  test_lib-networks:
    driver: bridge

volumes:
  test_lib-data-volume: